-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (1, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (2, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (3, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (4, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (5, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (6, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (7, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (8, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (9, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (10, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (11, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (12, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (13, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (14, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (15, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (16, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (17, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (18, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (19, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (20, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (21, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (22, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (23, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (24, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (25, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());

insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (27, 'CLASSIC', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (29, 'CITY', 'STANDARD', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (30, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (31, 'CLASSIC', 'STANDARD', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (32, 'CLASSIC', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (34, 'FOLDING', 'SMALL', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (35, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (39, 'CLASSIC', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (41, 'CLASSIC', 'SMALL', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (43, 'FOLDING', 'SMALL', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (44, 'CLASSIC', 'LARGE', 'FREE', true, false, now());
