-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (1, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (2, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (3, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (4, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (5, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (6, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (7, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (8, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (9, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (10, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (11, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (12, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (13, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (14, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (15, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (16, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (17, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (18, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (19, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (20, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (21, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (22, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (23, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (24, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());
-- insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (25, 'CLASSIC', 'STANDARD', 'FREE', true, true, now());

insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (40, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (41, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (42, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (43, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (44, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (45, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (46, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (47, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (48, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (49, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (50, 'CITY', 'LARGE', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (51, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (52, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (53, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (54, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (55, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (56, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (57, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (58, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (59, 'CITY', 'MEDIUM', 'FREE', true, false, now());
insert into bike(numbering, bike_type, size, current_status, is_active, is_classroom_bike, created_at) values (60, 'CITY', 'MEDIUM', 'FREE', true, false, now());
